### ISSUE TITLE
[Feature]: Plot uncorrected and corrected energy ratios to show impact of northing calibration

### ISSUE THREAD

**Issue by paulf81** [NREL/flasc#100]
### Description

Provide a standard tool to plot the energy ratio using the uncorrected wd and the northing corrected wd to demonstrate where the wd has been corrected to

**Comment by misi9170** [comment]
Working on this this week, will provide a link to a pull request once generated.

**Comment by misi9170** [comment]
Now addressed (I hope) in #105

**Comment by misi9170** [comment]
Closed by #105
