### ISSUE TITLE
conversion problem between pd.Timestamp and np.datetime64

### ISSUE THREAD

**Issue by ChristianBurth** [NREL/flasc#11]
I ran into a bug in flasc/optimization.py while running example a_06a where i got the following error on line 112 in find_timeshift_between_dfs:
`while current_time < max_time:`
> TypeError: Cannot compare tz-naive and tz-aware timestamps

pd.Timestamp objects generally have a reference to a timezone, while np.datetime64 objects do not.
In the first iteration this is not a problem as both current_time and max_time are defined from the timestamp in the dataframe which in the example are pd.Timestamp objects.
The problem arises in the while loop after current_time gets assigned a np.datetime64 in line 205.

I could fix this by changing the lines 109-112 to:
```
    current_time = np.datetime64(min_time)
    output_list = []
    print('Estimating required timeshift for df1.')
    while current_time < np.datetime64(max_time):
```

**Comment by Bartdoekemeijer** [comment]
Hi @ChristianBurth. Thank you for posting this issue! PR #14 has been created and merged into `main` to resolve the issue. Let me know if the latest `main` branch resolves your problem. It does, on my end. Thank you!
