### ISSUE TITLE
problem with default value in calc_floris_approx_table()

### ISSUE THREAD

**Issue by ChristianBurth** [NREL/flasc#12]
There is the function calc_floris_approx_table() in flasc/floris_tools.py which takes `ti_array` as an input value.
The default input value is set to `None` (so is the value in the example a_07a, where i encountered the problem)

But the function as it is does not work without at least one value in the `ti_array`

**Comment by Bartdoekemeijer** [comment]
Hi @ChristianBurth! Thanks for sharing and bringing my attention to this issue. I've created and merged in PR #13 which will make the function default to the current turbulence intensity in the floris object, in case `ti_array=None`. Let me know if the latest `main` branch resolves your issue!
