### ISSUE TITLE
[Documentation]: Delete old readthedocs page

### ISSUE THREAD

**Issue by paulf81** [NREL/flasc#131]
### Description

FLASC documentation migrated to github pages for consistency with FLORIS/HERCULES/etc, opening this issue just to flag we should at some point delete readthedocs site

### URL

https://flasc.readthedocs.io/en/latest/

**Comment by Bartdoekemeijer** [comment]
Would you like me to delete the readthedocs already, or would you like me to wait a little bit longer?

**Comment by Bartdoekemeijer** [comment]
Deleted!

**Comment by paulf81** [comment]
Thank you!
