### ISSUE TITLE
Add develop branch / standardize main versions

### ISSUE THREAD

**Issue by paulf81** [NREL/flasc#17]
Currently there is a single branch (main), should probably add a develop branch and make a plan for rolling develop to main, perhaps could ask @bayc  or @rafmudaf  for help here

**Comment by Bartdoekemeijer** [comment]
Good ideas, I'm all in favor!

**Comment by paulf81** [comment]
Nice to see you in github again!  Hope you're doing well!

I think @bayc will help @bayc  to make this happen

**Comment by bayc** [comment]
Done!
