### ISSUE TITLE
[BUG] Remove codecov bric-a-brac

### ISSUE THREAD

**Issue by paulf81** [NREL/flasc#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Codecov is always causing tests to fail with pull requests for issues I think pertaining more to github.com/codecov than anything we could fix, think we should find a way to yank it out

### Expected Behavior

Not getting a bunch of failing messages from codecov

### Environment

```markdown
- OS:
- pip environment (can be retrieved with `pip list`):
```

**Comment by Bartdoekemeijer** [comment]
Works for me. I'm not too experienced with codecov, so I'll leave that up to your judgement!
