### ISSUE TITLE
[Documentation]: Follow FLORIS documentation improvements

### ISSUE THREAD

**Issue by paulf81** [NREL/flasc#44]
### Description

@rafmudaf  is leading a major improvement to how FLORIS documentation is done.  This issue is to propose when that is complete we follow the same approach here on FLASC

**Comment by Bartdoekemeijer** [comment]
Sounds good to me!

**Comment by paulf81** [comment]
Noting that if FLASC won't have built in examples, the importance of the documentation goes up.  @rafmudaf , maybe I could connect with you on how we can mimic in flasc the plan for the new FLORIS style documentation?

**Comment by paulf81** [comment]
This is initiated if incomplete,
