### ISSUE TITLE
[Feature]: FLASC on PyPI

### ISSUE THREAD

**Issue by Bartdoekemeijer** [NREL/flasc#49]
### Description

I would like to have flasc available through PyPI such that we can include it and have it auto-installed through the `setup.py` Python module file, e.g., for #48.

Also, it would allow users to download `flasc` with a single call,
`pip install flasc`
`pip install flasc==1.0`

@rafmudaf were you the one to do this for `floris`? How complicated is this process?

**Comment by Bartdoekemeijer** [comment]
It appears that #88 stems from a problem with the PyPI installation. Let's revise any release a v1.4 soon, right after we merge #86.

**Comment by paulf81** [comment]
hi @Bartdoekemeijer do you know, is this issue resolved and we can close this one?

**Comment by Bartdoekemeijer** [comment]
Yes, resolved! Closing.
