### ISSUE TITLE
[Feature]: Rework examples around open Smarteole database

### ISSUE THREAD

**Issue by paulf81** [NREL/flasc#55]
### Description

A dataset from a wake steering campaign has been made publically available.  This data is provided by Engie from the Wind Farm Control campaign at Sole du Moulin Vieux and is available here:

https://zenodo.org/record/7342466

Further @ejsimley points us to code on how to download data from zenodo:

https://github.com/charlie9578/OpenOA/blob/feature/cubico-projects/examples/project_Cubico.py

Dataset should not need much filtering but can still probably show some pre-processing syntax, however, best opportunities are for showing SCADA / FLORIS analysis using real data . 

@Bartdoekemeijer wanted to flag you on this to bring

**Comment by Bartdoekemeijer** [comment]
Love this idea!

**Comment by paulf81** [comment]
@ejsimley is working on this one, but note this is now heading over to flasc_cookie_cutter here:

https://github.com/NREL/flasc_cookiecutter_template/issues/2

**Comment by Bartdoekemeijer** [comment]
Closing this one in that case, if you don't mind
